#!/usr/bin/env bash
# Idempotent Cloud Agent install for AI Film Studio (Nuxt 3 + PocketBase).
# Prepares durable repository state: node deps, PocketBase binary, local .env,
# and an initialized PocketBase data dir (superuser + collections).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PB_VERSION="0.36.7"
PB_DIR="$ROOT/pocketbase"
PB_BIN="$PB_DIR/pocketbase"
PB_ADMIN_EMAIL="${POCKETBASE_ADMIN_EMAIL:-admin@example.com}"
PB_ADMIN_PASSWORD="${POCKETBASE_ADMIN_PASSWORD:-changeme123456}"

echo "==> Installing node dependencies"
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

echo "==> Ensuring PocketBase binary (v${PB_VERSION})"
if [ ! -x "$PB_BIN" ] || ! "$PB_BIN" --version 2>/dev/null | grep -q "$PB_VERSION"; then
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) pb_arch="amd64" ;;
    aarch64|arm64) pb_arch="arm64" ;;
    *) echo "Unsupported architecture: $arch" >&2; exit 1 ;;
  esac
  url="https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_${pb_arch}.zip"
  tmpzip="$(mktemp)"
  curl -fsSL -o "$tmpzip" "$url"
  ( cd "$PB_DIR" && unzip -o "$tmpzip" pocketbase >/dev/null && chmod +x pocketbase )
  rm -f "$tmpzip"
fi
echo "    $($PB_BIN --version)"

echo "==> Ensuring .env"
if [ ! -f "$ROOT/.env" ]; then
  cat > "$ROOT/.env" <<EOF
# Local development environment (generated by .cursor/install.sh)
NUXT_PUBLIC_POCKETBASE_URL=http://127.0.0.1:8090
VITE_POCKETBASE_URL=http://127.0.0.1:8090
NUXT_POCKETBASE_INTERNAL_URL=http://127.0.0.1:8090
POCKETBASE_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
POCKETBASE_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
# OPENROUTER_API_KEY is read from the environment (add it as a secret to enable AI features).
EOF
fi

echo "==> Creating PocketBase superuser"
( cd "$PB_DIR" && ./pocketbase superuser upsert "$PB_ADMIN_EMAIL" "$PB_ADMIN_PASSWORD" )

echo "==> Initializing PocketBase collections"
# Briefly run PocketBase so the setup script can create collections, then stop it.
if lsof -nP -iTCP:8090 -sTCP:LISTEN -t >/dev/null 2>&1; then
  echo "    PocketBase already listening on :8090 — using it"
  npm run setup-db
else
  ( cd "$PB_DIR" && ./pocketbase serve --http=127.0.0.1:8090 >/tmp/pb-install.log 2>&1 ) &
  PB_PID=$!
  for i in $(seq 1 30); do
    if curl -sf http://127.0.0.1:8090/api/health >/dev/null 2>&1; then break; fi
    sleep 1
  done
  npm run setup-db
  kill "$PB_PID" 2>/dev/null || true
  wait "$PB_PID" 2>/dev/null || true
fi

echo "==> Install complete"
